[project]
name = "trabalho-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "pyinstaller>=6.16.0",
    "pytest>=9.0.1",
]

[project.scripts]
build-bin = "build_bin:build"

[build-system]
requires = ["setuptools>=68.0.0", "wheel"]
build-backend = "setuptools.build_meta"
